---
- hosts: localhost
  become: yes
  tasks:
    # VPC #
    - name: Create VPC
      ec2_vpc_net:
        aws_access_key: "<YOUR ACCESS KEY>"
        aws_secret_key: "<YOUR SECRET KEY>"
        cidr_block: 10.0.0.0/16
        region: us-east-2
        name: ansible-vpc
        state: present
        tags:
          Name: ansible-vpc
      register: vpc

    # INTERNET GATEWAY #
    - name: Create Internet Gateway
      ec2_vpc_igw:
        aws_access_key: "<YOUR ACCESS KEY>"
        aws_secret_key: "<YOUR SECRET KEY>"
        vpc_id: "{{ vpc.vpc.id }}"
        region: us-east-2
        state: present
        tags:
          Name: ansible-igw
      register: igw

    # PUBLIC SUBNET #
    - name: Create public subnet
      ec2_vpc_subnet:
        aws_access_key: "<YOUR ACCESS KEY>"
        aws_secret_key: "<YOUR SECRET KEY>"
        vpc_id: "{{ vpc.vpc.id }}"
        region: us-east-2
        az: us-east-2a
        state: present
        cidr: 10.0.1.0/24
        map_public: yes
        tags:
          Name: ansible-pub-sub
      register: pubsubnet

    # PRIVATE SUBNET #
    - name: Create private subnet
      ec2_vpc_subnet:
        aws_access_key: "<YOUR ACCESS KEY>"
        aws_secret_key: "<YOUR SECRET KEY>"
        vpc_id: "{{ vpc.vpc.id }}"
        region: us-east-2
        az: us-east-2b
        state: present
        cidr: 10.0.2.0/24
        map_public: no
        tags:
          Name: ansible-pvt
      register: pvtsubnet

    # PUBLIC ROUTE TABLE #
    - name: Create public route table
      ec2_vpc_route_table:
        aws_access_key: "<YOUR ACCESS KEY>"
        aws_secret_key: "<YOUR SECRET KEY>"
        vpc_id: "{{ vpc.vpc.id }}"
        region: us-east-2
        state: present
        tags:
          Name: ansible-pub-rt
        subnets:
          - "{{ pubsubnet.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{igw.gateway_id}}"
      register: publicrt

    # PRIVATE ROUTE TABLE #
    - name: Create private route table
      ec2_vpc_route_table:
        aws_access_key: "<YOUR ACCESS KEY>"
        aws_secret_key: "<YOUR SECRET KEY>"
        vpc_id: "{{ vpc.vpc.id }}"
        region: us-east-2
        state: present
        tags:
          Name: ansible-pvt-rt
        subnets:
          - "{{ pvtsubnet.subnet.id }}"
      register: privatert

    # SECURITY GROUP #
    - name: Create security group
      ec2_group:
        aws_access_key: "<YOUR ACCESS KEY>"
        aws_secret_key: "<YOUR SECRET KEY>"
        vpc_id: "{{ vpc.vpc.id }}"
        region: us-east-2
        state: present
        name: ansible-sg
        description: Allow All Traffic
        tags:
          Name: ansible-sg
        rules:
          - proto: all
            cidr_ip: 0.0.0.0/0
            rule_desc: "allow all traffic"
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
            rule_desc: "Allow all outbound traffic"
      register: securitygroup

    # EC2 INSTANCE #
    - name: Create EC2 instance
      ec2:
        aws_access_key: "<YOUR ACCESS KEY>"
        aws_secret_key: "<YOUR SECRET KEY>"
        image: "ami-00cda30cf72311684"
        instance_type: t2.micro
        region: us-east-2
        count: 1
        state: present
        vpc_subnet_id: "{{ pubsubnet.subnet.id }}"
        assign_public_ip: yes
        group_id: "{{ securitygroup.group_id }}"
        key_name: "p5-key"
        instance_tags:
          Name: ansible
        user_data: "{{ lookup('file', 'setup.sh') }}"
      register: ec2instance


